#!/usr/bin/env python

"""Django Buildr

Usage:
  django-buildr generate <target> [--template=<default>]
  django-buildr (-h | --help)
  django-buildr --version

Options:
  --template=<default>  Project template [default: default].
  -h --help             Show this screen.
  --version             Show version.
"""
from importlib import import_module
from os.path import join, abspath, dirname
from docopt import docopt

from generate import Command

PLUGINS = ('south.SouthPlugin', 'debug_toolbar.DebugToolbarPlugin')


if __name__ == '__main__':

    kwargs = docopt(__doc__, version='Django Buildr 0.1')
    templates_dir = 'templates'
    kwargs['template'] = join(abspath(dirname(__file__)), "%s/%s" % (templates_dir, kwargs['--template']))
    kwargs['extensions'] = ['py', 'txt']

    for plugin in PLUGINS:
        module, klass = plugin.split('.')
        PluginClass = getattr(import_module('plugins.%s' % module), klass)
        should_enable = raw_input('%s :: %s | Enable? (Y/n) ' % (PluginClass.name, PluginClass.description))
        if should_enable.lower() == 'y':
            for k, v in PluginClass().get_context().iteritems():
                if k in kwargs:
                    kwargs[k].extend(v)
                else:
                    kwargs[k] = v

    args = (kwargs['<target>'], )

    Command().execute(*args, **kwargs)
