#!/usr/bin/env python

"""Django Mason

Usage:
  django-mason generate <target> [--template=<default>]
  django-mason (-h | --help)
  django-mason --version

Options:
  --template=<default>  Project template [default: default].
  -h --help             Show this screen.
  --version             Show version.
"""
from importlib import import_module
from os.path import join, abspath, dirname
from docopt import docopt

from generate import Command

from conf import PLUGINS


def get_plugin_class(plugin_path):
    try:
        module, classname = plugin_path.rsplit('.', 1)
    except ValueError:
        raise Exception('%s isn\'t a middleware module' % plugin_path)
    try:
        mod = import_module(module)
    except ImportError as e:
        raise Exception('Error importing middleware %s: "%s"' % (module, e))
    try:
        klass = getattr(mod, classname)
    except AttributeError:
        raise Exception('Middleware module "%s" does not define a "%s" class' % (module, classname))
    return klass


if __name__ == '__main__':

    kwargs = docopt(__doc__, version='Django Mason 0.1')
    templates_dir = 'templates'
    kwargs['template'] = join(abspath(dirname(__file__)), "%s/%s" % (templates_dir, kwargs['--template']))
    kwargs['extensions'] = ['py', 'txt']

    for plugin_path in PLUGINS:
        PluginClass = get_plugin_class(plugin_path)
        plugin = PluginClass()
        should_enable = plugin.ask()
        if should_enable:
            for k, v in plugin.get_context().iteritems():
                if k in kwargs and type(v) == list:
                    kwargs[k].extend(v)
                else:
                    kwargs[k] = v

    args = (kwargs['<target>'], )

    Command().execute(*args, **kwargs)
