#!/usr/bin/env python

"""Django Mason

Usage:
  django-mason generate <target> [--template=<default>]
  django-mason (-h | --help)
  django-mason --version

Options:
  --template=<default>  Project template [default: default].
  -h --help             Show this screen.
  --version             Show version.
"""
from importlib import import_module
from os.path import join, abspath, dirname
from docopt import docopt

from generate import Command

PLUGINS = ('south.South', 'debug_toolbar.DebugToolbar')


if __name__ == '__main__':

    kwargs = docopt(__doc__, version='Django Mason 0.1')
    templates_dir = 'templates'
    kwargs['template'] = join(abspath(dirname(__file__)), "%s/%s" % (templates_dir, kwargs['--template']))
    kwargs['extensions'] = ['py', 'txt']

    for plugin_path in PLUGINS:
        module, klass = plugin_path.split('.')
        PluginClass = getattr(import_module('bricks.%s' % module), klass)
        plugin = PluginClass()
        should_enable = plugin.ask()
        if should_enable:
            for k, v in plugin.get_context().iteritems():
                if k in kwargs and type(v) == list:
                    kwargs[k].extend(v)
                else:
                    kwargs[k] = v

    args = (kwargs['<target>'], )

    Command().execute(*args, **kwargs)
