#!/usr/bin/env python

"""Django Buildr

Usage:
  django-buildr generate [--base=<default>]
  django-buildr (-h | --help)
  django-buildr --version

Options:
  -h --help         Show this screen.
  --base=<default>  Speed in knots [default: 'default'].
  --version         Show version.
"""
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__, version='Django Buildr 0.1')
    print(arguments)
