PLUGINS = (
    'mason.bricks.database.Database',
    'mason.bricks.admin.Admin',
    'mason.bricks.grappelli.Grappelli',
    'mason.bricks.guardian.Guardian',
    'mason.bricks.south.South',
    'mason.bricks.debug_toolbar.DebugToolbar',
    'mason.bricks.fabfile.fabfile.Fabfile',
    'mason.bricks.sentry.Sentry',
    'mason.bricks.parsley.Parsley',
    'mason.bricks.travis.travis.Travis',
    'mason.bricks.crispy_forms.CrispyForms',
    'mason.bricks.disqus.Disqus',
    'mason.bricks.celery.Celery',
    'mason.bricks.nose.Nose',
    'mason.bricks.extensions.Extensions',
)
